# Generated by Django 2.2.7 on 2019-11-06 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191106_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbank',
            name='comment',
        ),
        migrations.AddField(
            model_name='questionbank',
            name='file_field',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
