# Generated by Django 2.2.7 on 2019-11-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191106_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbank',
            name='date_posted',
        ),
    ]
