# Generated by Django 2.2.7 on 2019-11-06 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_questionbank_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
