# Generated by Django 2.2.7 on 2019-11-06 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_questionbank_file_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='file_field',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
