# Generated by Django 2.2.7 on 2019-11-22 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_questionbank_file_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='answer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=9),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='marks',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionbank',
            name='statement',
            field=models.TextField(default="old"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionbank',
            name='tags',
            field=models.TextField(default="Not required"),
            preserve_default=False,
        ),
    ]
