# Generated by Django 2.2.7 on 2019-11-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191122_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
