# Generated by Django 2.2.7 on 2019-11-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20191123_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
