# Generated by Django 2.2.7 on 2019-11-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20191123_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='file_field',
        ),
        migrations.AlterField(
            model_name='question',
            name='isRoot',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questionmodule',
            name='isRoot',
            field=models.IntegerField(),
        ),
    ]
