# Generated by Django 2.2.7 on 2019-11-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='isRoot',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='parent',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
