# Generated by Django 2.2.7 on 2019-11-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_quizpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustToChose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=9)),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='tags',
            new_name='chapter_tag',
        ),
        migrations.AddField(
            model_name='question',
            name='section_tag',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
