# Generated by Django 2.2.7 on 2019-11-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20191124_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='chapter_tag',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='section_tag',
            field=models.CharField(max_length=1000),
        ),
    ]
