# Generated by Django 2.2.7 on 2019-11-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_uploadedfile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='title',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
