# Generated by Django 2.2.7 on 2019-11-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20191125_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
