# Generated by Django 2.2.7 on 2019-11-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20191125_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='title',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
