# Generated by Django 2.2.7 on 2019-11-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20191125_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizpaper',
            name='title',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
